FROM ghcr.io/userver-framework/ubuntu-24.04-userver:v2.15 AS builder

WORKDIR /build

COPY . .

RUN --mount=type=cache,target=/build/build-debug \
    --mount=type=cache,target=/build/.ccache \
    make build-debug -j$(nproc) \
    && cp /build/build-debug/api_gateway /build/api_gateway \
    && cp -r /build/build-debug/static /build

FROM ghcr.io/userver-framework/ubuntu-24.04-userver:v2.15

RUN groupadd -g 1500 api_gateway
RUN useradd -u 1500 -g api_gateway -m -s /bin/bash api_gateway

RUN mkdir -p /etc/api_gateway
RUN mkdir -p /etc/api_gateway/config

COPY --from=builder /build/api_gateway /usr/bin/api_gateway
COPY --from=builder /build/configs/static_config.yaml /etc/api_gateway/config/static_config.yaml
COPY --from=builder /build/configs/config_vars.yaml /etc/api_gateway/config/config_vars.yaml
COPY --from=builder /build/static /etc/api_gateway/static

WORKDIR /etc/api_gateway
USER api_gateway
EXPOSE 8080

ENV USERVER_ENABLE_STACK_USAGE_MONITOR=0
ENV DOCS_STATIC_FILES_PATH=/etc/api_gateway/static/docs
ENV USERVER_DNS_RESOLVER_MODE=system

CMD [ "/bin/sh", "-c", "CPU_LIMIT=$(nproc)c /usr/bin/api_gateway --config /etc/api_gateway/config/static_config.yaml --config_vars /etc/api_gateway/config/config_vars.yaml" ]
