components_manager:
    task_processors:

        main-task-processor:
            worker_threads: $worker-threads

        fs-task-processor:
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:
        server:
            listener:
                port: $server-port
                task_processor: main-task-processor

        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard

        dynamic-config:
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000

        testsuite-support: {}

        congestion-control:

        http-client:
        http-client-core:
            load-enabled: $is_testing
            fs-task-processor: fs-task-processor

        dns-client:
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor

        # Project components

        credentials-storage:
            load-enabled: true

        auth-checker:
            load-enabled: true

        # HTTP endpoint handlers

        register-handler:
            path: /register
            method: POST

        login-handler:
            path: /login
            method: POST

        info-handler:
            path: /info
            method: GET
            auth:
                types:
                - simple-auth
