FROM ghcr.io/userver-framework/ubuntu-22.04-userver-pg-dev:v2.15

RUN id -nu 1000

# RUN groupadd -g 1000 ubuntu
# RUN useradd -u 1000 -g 1000 -m -s /bin/bash ubuntu
# RUN usermod -aG sudo ubuntu
# RUN echo 'ubuntu ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/ubuntu
# RUN chmod 0440 /etc/sudoers.d/ubuntu

# USER ubuntu
