version: '3.8'

services:
  mongo_database:
    build:
      context: ../mongo
      dockerfile: Dockerfile
    container_name: mongo-database
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile
    image: api_gateway:latest
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ACCESS_SECRET=${ACCESS_SECRET}
      - REFRESH_SECRET=${REFRESH_SECRET}
      - DB_CONNECTION=mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@database:27017/${MONGO_DATABASE}?authSource=admin
    depends_on:
      - mongo_database
