openapi: 3.0.4

info:
  title: Property Service - OpenAPI 3.0
  description: |-
    A service for managing real estate and making an appointment to view it
  termsOfService: https://swagger.io/terms/
  contact:
    email: property-service@example.com
  version: 1.0.0

servers:
- url: https://localhost:8080

tags:
- name: auth
  description: Endpoints related to authorization

- name: property
  description: Endpoints related to property

- name: user
  description: Endpoints related to user

- name: viewing
  description: Endpoint related to viewing

paths:
  /register:
    post:
      tags: [ auth ]
      summary: Register a new user
      operationId: registerUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequestBody'
        required: true
      responses:
        '201':
          description: User registered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TokenPair"
        '400':
          description: Invalid payload
        '409':
          description: User with specified login lready exists

  /login:
    post:
      tags: [ auth ]
      summary: Login with specified credentials
      operationId: loginUser
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequestBody'
        required: true
      responses:
        '200':
          description: Login success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenPair'
        '400':
          description: Invalid payload
        '401':
          description: Bad credentials

  /users:
    get:
      tags: [ user ]
      summary: Find users by specified filters
      operationId: findUsers
      parameters:
      - name: login
        in: query
        description: Login mask
        required: false
        explode: true
        schema:
          type: string
      - name: firstName
        in: query
        description: First name of user
        required: false
        explode: true
        schema:
          type: string
      - name: lastName
        in: query
        description: Last name of user
        required: false
        explode: true
        schema:
          type: string
      responses:
        '200':
          description: Users found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserIds'

  /users/{userId}:
    get:
      tags: [ user ]
      summary: Get user info by specified ID
      operationId: getUserInfo
      parameters:
      - name: userId
        in: path
        description: ID of user
        required: true
        schema:
          type: string
      responses:
        '200':
          description: User found
          content:
            appliction/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '404':
          description: User not found

  /users/me:
    get:
      tags: [ user ]
      summary: Get information about current user
      operationId: getCurrentUser
      security:
      - bearerAuth: []
      responses:
        '200':
          description: User found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
  /properties:
    post:
      tags: [ property ]
      summary: Create new property
      operationId: createProperty
      security:
      - bearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreatePropertyRequestBody'
        required: true
      responses:
        '200':
          description: Property created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Property'
        '400':
          description: Invalid payload

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    RegisterRequestBody:
      type: object
      additionalProperties: false
      properties:
        login:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 1
        firstName:
          type: string
          minLength: 1
        lastName:
          type: string
          minLength: 1
      required:
      - login
      - password
      - firstName
      - lastName

    TokenPair:
      type: object
      additionalProperties: false
      properties:
        accessToken:
          type: string
          minLength: 1
        refreshToken:
          type: string
          minLength: 1
      required:
      - accessToken
      - refreshToken

    LoginRequestBody:
      type: object
      additionalProperties: false
      properties:
        login:
          type: string
          minLength: 1
        password:
          type: string
          minLength: 1
      required:
      - login
      - password

    UserIds:
      type: object
      additionalProperties: false
      properties:
        userIds:
          type: array
          items:
            type: string
            minLength: 1
      required:
      - userIds

    UserInfo:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
          minLength: 1
        login:
          type: string
          minLength: 1
        firstName:
          type: string
          minLength: 1
        lastName:
          type: string
          minLength: 1
      required:
      - id
      - login
      - firstName
      - lastName

    PropertyStatus:
      type: string
      enum: [ "active", "sold" ]

    Address:
      type: object
      additionalProperties: false
      properties:
        country:
          type: string
          minLength: 1
        city:
          type: string
          minLength: 1
        street:
          type: string
          minLength: 1
        building:
          type: integer
          format: int32
          minimum: 1
        apartment:
          type: integer
          format: int32
          minimum: 1
      required:
      - country
      - city
      - street
      - building
      - apartment

    Property:
      type: object
      additionalProperties: false
      properties:
        id:
          type: string
          minLength: 1
        address:
          $ref: '#/components/schemas/Address'
        ownerId:
          type: string
          minLength: 1
        status:
          $ref: '#/components/schemas/PropertyStatus'
        price:
          type: integer
          minimum: 1
      required:
      - id
      - address
      - ownerId
      - status
      - price

    CreatePropertyRequestBody:
      type: object
      additionalProperties: false
      properties:
        address:
          $ref: "./common.yaml#/components/schemas/Address"
        price:
          type: integer
          minimum: 1
      required:
      - address
      - price
